apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-user
  template:
    metadata:
      labels:
        app: grpc-user
    spec:
      containers:
      - name: grpc-user-container
        image: grpc-user:v1 # O nome da segunda imagem
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-user-service
spec:
  type: NodePort
  selector:
    app: grpc-user
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
